version: '3.5'
services:
  server:
    build: .
    environment:
      - PORT=3002
    ports:
      - "3002:3002"
    networks:
      - docker-net
  web:
    build:
      context: ./web
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    networks:
      - docker-net
networks:
  docker-net:
